In [1]:
import sys
sys.path.append('../')

In [2]:
from utils import *
from transforms import Fully_Connected_Graph, Graph_to_Subgraph
from trainers.get_qm9 import get_qm9

In [3]:
fully_connected_edge_index(5)

tensor([[0, 0, 0, 0, 1, 1, 1, 2, 2, 3, 1, 2, 3, 4, 2, 3, 4, 3, 4, 4],
        [1, 2, 3, 4, 2, 3, 4, 3, 4, 4, 0, 0, 0, 0, 1, 1, 1, 2, 2, 3]])

In [4]:
# make a small edge index
edge_index = torch.tensor([[2,3,4,5],
                           [6,2,3,3]], dtype=torch.long)

In [5]:
fully_connect_existing_nodes(edge_index)

tensor([[2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6],
        [3, 4, 5, 6, 2, 4, 5, 6, 2, 3, 5, 6, 2, 3, 4, 6, 2, 3, 4, 5]])

In [7]:
# get one data point
data = get_qm9(data_dir="../data/", transform=Fully_Connected_Graph())
train_data = data[0]
datapoint = train_data[0]
datapoint.edge_index

In [ ]:
# See for subgraphs

In [5]:
# get one data point
data = get_qm9(data_dir="../data/", transform=Graph_to_Subgraph(fully_connect=True))
test_data = data[2]
datapoint = test_data[0]
print(datapoint.edge_index)
print(datapoint.subgraph_edge_index)

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,
          2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
          3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,
          4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
          5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
          6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
          7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
          9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11,
         11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12,
         12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13,
         13, 13, 13, 13, 13,

In [19]:
# See for subgraphs without the transform
# get one data point
data = get_qm9(data_dir="../data/", transform=Graph_to_Subgraph(fully_connect=False))
test_data = data[0]
datapoint = test_data[205]
print(datapoint.edge_index)
print(datapoint.subgraph_edge_index)

tensor([[0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 7, 8],
        [1, 6, 0, 2, 5, 1, 3, 7, 2, 4, 3, 5, 8, 1, 4, 0, 2, 4]],
       device='cuda:0')
tensor([[ 9,  9, 10, 10, 10, 11, 11, 11, 12, 12, 13, 13, 13, 14, 14, 15, 16, 17,
         18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 22, 22, 22, 23, 23, 24, 25, 26,
         27, 27, 28, 28, 28, 29, 29, 29, 30, 30, 31, 31, 31, 32, 32, 33, 34, 35,
         36, 36, 37, 37, 37, 38, 38, 38, 39, 39, 40, 40, 40, 41, 41, 42, 43, 44,
         45, 45, 46, 46, 46, 47, 47, 47, 48, 48, 49, 49, 49, 50, 50, 51, 52, 53,
         54, 54, 55, 55, 55, 56, 56, 56, 57, 57, 58, 58, 58, 59, 59, 60, 61, 62,
         63, 63, 64, 64, 64, 65, 65, 65, 66, 66, 67, 67, 67, 68, 68, 69, 70, 71,
         72, 72, 73, 73, 73, 74, 74, 74, 75, 75, 76, 76, 76, 77, 77, 78, 79, 80,
         81, 81, 82, 82, 82, 83, 83, 83, 84, 84, 85, 85, 85, 86, 86, 87, 88, 89],
        [10, 15,  9, 11, 14, 10, 12, 16, 11, 13, 12, 14, 17, 10, 13,  9, 11, 13,
         19, 24, 18, 20, 23, 19, 21,

In [22]:
# Go through train, valid and test dataloader and check the average molecule size.
train, valid, test = get_qm9(data_dir="../data/", transform=None)

for dataset in [train, valid, test]:
    avg_size = 0
    for datapoint in dataset:
        avg_size += datapoint.num_nodes
    avg_size /= len(dataset)
    print(avg_size)

17.81263
19.9624
18.161538092266333


In [5]:
# Go through train dataset and give me a datapoint with 5 or less nodes
train, valid, test = get_qm9(data_dir="../data/", transform=None)
for datapoint in train:
    if 8 > datapoint.num_nodes > 5:
        small_datapoint = datapoint
        break

/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py:157: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [28]:
from torch_geometric.loader import DataLoader
def get_datasets(data_dir, device, LABEL_INDEX, subgraph, batch_size, fully_connect=False):
    if subgraph:
        transform = Graph_to_Subgraph(fully_connect=fully_connect)
        print("Using subgraph dataset.\n")
        print("Using fully connected subgraph dataset: ", fully_connect)
    elif fully_connect and not subgraph:
        transform = Fully_Connected_Graph()
        print("Using fully connected regular dataset.\n")
    else:
        transform = None
        print("Using regular dataset.\n")

    train, valid, test = get_qm9(data_dir, device=device, LABEL_INDEX=LABEL_INDEX, transform=transform)
    train_loader = DataLoader(train, batch_size=batch_size, shuffle=True)
    valid_loader = DataLoader(valid, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test, batch_size=batch_size, shuffle=False)
    return train_loader, valid_loader, test_loader


In [29]:
train, valid, test = get_datasets("../data", 'cpu', 7, False, 32, False)

Using regular dataset.



In [32]:
train.dataset.data.y

tensor([[  0.0000,  13.2100, -10.5499,  ..., 157.7118, 157.7100, 157.7070],
        [  1.6256,   9.4600,  -6.9933,  ..., 293.6097, 293.5411, 191.3940],
        [  1.8511,   6.3100,  -7.9675,  ..., 799.5881, 437.9039, 282.9455],
        ...,
        [  1.2480,  73.6000,  -6.0763,  ...,   3.6712,   2.1431,   1.8950],
        [  1.9576,  77.4000,  -5.7743,  ...,   3.5285,   2.1513,   1.8658],
        [  0.8626,  69.4800,  -6.3022,  ...,   3.6402,   2.2176,   1.9379]])

In [4]:
small_datapoint.edge_index

tensor([[0, 0, 0, 0, 1, 1, 2, 2, 3, 4, 5, 6],
        [1, 3, 4, 5, 0, 2, 1, 6, 0, 0, 0, 2]], device='cuda:0')

In [9]:
transform_1 = Graph_to_Subgraph(fully_connect=False)
transform_2 = Graph_to_Subgraph(fully_connect=True)

# clone the small datapoint
small_datapoint_1 = small_datapoint.clone()
small_datapoint_2 = small_datapoint.clone()

small_datapoint_1 = transform_1(small_datapoint)
small_datapoint_2 = transform_2(small_datapoint)

print(small_datapoint_1.edge_index)
print(small_datapoint_2.edge_index)

print('\n')
print(small_datapoint_1.subgraph_edge_index[:, :15])
print(small_datapoint_2.subgraph_edge_index[:, :40])

tensor([[0, 0, 0, 0, 1, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 0, 5, 0, 0, 0, 1]], device='cuda:0')
tensor([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,
         4, 5, 5, 5, 5, 5],
        [1, 2, 3, 4, 5, 0, 2, 3, 4, 5, 0, 1, 3, 4, 5, 0, 1, 2, 4, 5, 0, 1, 2, 3,
         5, 0, 1, 2, 3, 4]], device='cuda:0')


tensor([[ 6,  6,  6,  6,  7,  7,  8,  9, 10, 11, 12, 12, 12, 12, 13],
        [ 7,  8,  9, 10,  6, 11,  6,  6,  6,  7, 13, 14, 15, 16, 12]],
       device='cuda:0')
tensor([[ 6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,
          9,  9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13,
         13, 13, 13, 13],
        [ 7,  8,  9, 10, 11,  6,  8,  9, 10, 11,  6,  7,  9, 10, 11,  6,  7,  8,
         10, 11,  6,  7,  8,  9, 11,  6,  7,  8,  9, 10, 13, 14, 15, 16, 17, 12,
         14, 15, 16, 17]], device='cuda:0')
